website/urls.py
from django.urls import include, path

from website import views
from website.views import api, discord, news


app_name = 'website'
urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.logout, name='logout'),

    path('api/', include([
        path('', api.api_root, name='api'),
        
        path('username-chat/', include([
            path('', api.change_username),
        ])),
        
        path('dynamic-username/', include([
            path('', api.dynamic_username_root),
        ])),
    ])),

    path('discord/', include([
        path('user/', discord.discord_user_info, name='user'),
        
        path('auth/', include([
            path('', discord.discord_auth, name='discord_auth'),
            path('url/', discord.discord_auth_url,
                 name='discord_auth_url'),
        ])),
    ])),

    path('news/', views.news.news_root, name='news'),
]

website/models.py
from datetime import datetime

from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class DiscordToken(models.Model):
    """Discord's user token for authentication"""
    access_token = models.CharField(max_length=128)
    token_type = models.CharField(max_length=20)
    last_time_updated = models.DateTimeField(auto_now=True)
    expires_in = models.DurationField()
    refresh_token = models.CharField(max_length=128)
    scope = models.CharField(max_length=20)
    redirect_uri = models.TextField()

    @property
    def valid_till(self):
        return self.last_time_updated + self.expires_in
    
    @property
    def is_expired(self) -> bool:
        return self.valid_till < timezone.now()

    def __str__(self) -> str:
        return f"{self.access_token} \
        ({self.last_time_updated} - {self.valid_till})"


class DiscordUser(models.Model):
    """User auth credentials to use Discord API"""
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="discord_user"
    )
    token = models.OneToOneField(
        DiscordToken,
        on_delete=models.CASCADE,
        related_name="discord_user",
        null=True, blank=True
    )
    username = models.CharField(max_length=32, null=True, blank=True)
    discord_user_id = models.CharField(max_length=64, null=True, blank=True)
    avatar = models.CharField(max_length=512, null=True, blank=True)

    @property
    def avatar_url(self) -> str:
        image_base_url = "https://cdn.discordapp.com/"
        avatar_url = "embed/avatars/0.png"

        if self.discord_user_id and self.avatar: 
            avatar_url = f"avatars/{self.discord_user_id}/{self.avatar}."
            avatar_url += "gif" if str(self.avatar).startswith("a_") else "png"

        return image_base_url + avatar_url

    def __str__(self) -> str:
        return str(self.username or self.user.username)


class UsernameMessage(models.Model):
    """User's name as messages"""
    discord_user = models.ForeignKey(
        DiscordUser,
        on_delete=models.CASCADE,
        related_name='messages'
    )
    text = models.CharField(max_length=32)
    sent = models.DateTimeField(auto_now_add=True)

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude)

        restricted_words = {
            "everyone", "here", "discordtag", "@", "#", ":", "`"
        }

        if not (2 <= len(self.text) <= 32):
            raise ValidationError(
                "Длинна никнейма должна быть от 2х до 32х симовлов."
            )


        if any(word in str(self.text).lower() for word in restricted_words):
            raise ValidationError(
                "Никнейм не должен содержать следующие символы: '" + 
                "', '".join(restricted_words) + "'."
            )

    def __str__(self) -> str:
        return f"({self.sent}) {self.text} by {self.discord_user}"

website/views/api.py
from typing import Dict
from datetime import datetime
from collections import namedtuple

from django.http import JsonResponse
from django.utils.dateformat import format

from i_cant_chat.settings import DATETIME_FORMAT

from website.selectors import get_user_token
from website.services import ServiceError, discord
from website.models import DiscordToken, UsernameMessage


ApiResponse = namedtuple('ApiResponse', ['status', 'type', 'text'])


class ApiMethod:
    NOT_IMPLEMENTED_WARN = ApiResponse(
        status='warning',
        type='Not implemented',
        text='This function has not been implemented yet.'
    )

    NOT_AUTH_ERROR = ApiResponse(
        status='error',
        type='Not Authentiacted',
        text='You are not authenticated.'
    )

    WRONG_METHOD_ERROR = ApiResponse(
        status='error',
        type='Wrong method type',
        text='You should use POST method only.'
    )

    WRONG_ARGS_PASSED_ERROR = ApiResponse(
        status='error',
        type='Wrong arguments.',
        text='Wrong arguments passed to the API method.'
    )

    EMPTY_RESPONSE_ERROR = ApiResponse(
        status='error',
        type='Empty API response.',
        text='Got empty response from the API method.'
    )

    def __init__(self, method_args: set=set(), implemented: bool=True):
        self._method_args = method_args
        self._implemented = implemented

    @staticmethod
    def get_date():
        return format(datetime.now(), DATETIME_FORMAT)

    @staticmethod
    def api_response(func):
        def wrapper(*args, **kwargs):
            result:ApiResponse = func(*args, **kwargs)
            dict_result = result._asdict()
            dict_result["date"] = ApiMethod.get_date()
            return JsonResponse(dict_result)
        return wrapper

    def __call__(self, func):
        @ApiMethod.api_response
        def wrapper(*args, **kwargs) -> ApiResponse:
            request = args[0] # must be request
            if not self._implemented:
                return self.NOT_IMPLEMENTED_WARN

            if not request.user.is_authenticated:
                return self.NOT_AUTH_ERROR
            
            if request.method != "POST":
                return self.WRONG_METHOD_ERROR

            if not all(arg in request.POST.keys() for arg in self._method_args):
                return self.WRONG_ARGS_PASSED_ERROR

            for method_arg in self._method_args:
                kwargs[method_arg] = request.POST[method_arg]

            try:
                return func(*args, **kwargs) or self.EMPTY_RESPONSE_ERROR
            except ServiceError as e:
                return ApiResponse(status="error", type=e.text, text=e.details)
        return wrapper


@ApiMethod(implemented=False)
def api_root(request):
    pass


@ApiMethod({"username"})
def change_username(request, username=""):
    discord_user_id = request.user.username
    token: DiscordToken = get_user_token(discord_user_id)

    if token is None:
        return ApiResponse(
            status="error",
            type="Ошибка получения токена.",
            text=f"Токен пользователя {discord_user_id} не найден в базе."
        )

    if token.is_expired:
        discord.refresh_token(token)
    
    username_message: UsernameMessage = discord.create_username_message(
        token, username
    )

    return ApiResponse(
        status="success",
        type="Никнейм успешно изменен.",
        text=username_message.text
    )


@ApiMethod(implemented=False)
def dynamic_username_root(request):
    pass

website/views/discord.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.urls import reverse

from website.services import ServiceError, discord
from website.selectors import get_discord_user, get_username_messages
from website.views import error_403, error_500
from website.models import DiscordToken, DiscordUser


def _get_absolute_url(request, url_name: str) -> str:
    # Discord doesn't like trailing '/' symbol.
    return request.build_absolute_uri(reverse(url_name))[:-1]


def discord_auth_url(request):
    test_redirect_uri = _get_absolute_url(request, 'website:discord_auth')
    auth_url = discord.get_auth_url(test_redirect_uri)
    return redirect(auth_url)


def discord_auth(request):
    code = request.GET.get('code', None)
    if code is None:
        return error_500(request, details="Нет кода для аутентификации.")

    try:
        redirect_uri = _get_absolute_url(request, 'website:discord_auth')
        token: DiscordToken = discord.create_token(code, redirect_uri)
        user: DiscordUser = discord.create_user(token)
        login(request, user)
        return redirect('website:index')
    except ServiceError as e:
        return error_500(request, details=str(e))


def discord_user_info(request):
    if not request.user.is_authenticated:
        return error_403(request, details="Необходимо войти с помощью Discord.")

    # request.user.username should be equal to 
    # request.user.discord_user.discord_user_id, if it is not - 
    # None will be returned
    discord_user_id = request.user.username
    return render(request, 'website/user.html', context={
        'discord_user': get_discord_user(discord_user_id),
        'last_messages': get_username_messages(discord_user_id, 5)
    })

website/views/news.py
from django.shortcuts import render


def news_root(request):
    return render(request, 'website/news.html')

website/templates/website/base.html
{% load static %}

<!DOCTYPE HTML5>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>I can't chat</title>
</head>
<body class="website-body container">
    <header class="my-2">
        <nav class="navbar navbar-expand-lg navbar-dark website-header">
            <a class="navbar-brand" href="{% url 'website:index' %}">
                <img src="{% static 'img/cant-speak-icon.png' %}" width="30" height="30" class="d-inline-block" loading="lazy">
                I Can't Chat
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% block menu %}
                {% endblock %}
                {% if user.is_authenticated and discord_user %}
                <a class="btn website-button" href="{% url 'website:user' %}">
                    <img src="{{ discord_user.avatar_url }}" width="30" height="30" class="d-inline-block rounded-circle mx-1" loading="laze">
                    <span id="original-nickname">{{ discord_user }}</span>
                </a>
                <a class="btn website-button" href="{% url 'website:logout' %}">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-box-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M11.646 11.354a.5.5 0 0 1 0-.708L14.293 8l-2.647-2.646a.5.5 0 0 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0z"/>
                        <path fill-rule="evenodd" d="M4.5 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5z"/>
                        <path fill-rule="evenodd" d="M2 13.5A1.5 1.5 0 0 1 .5 12V4A1.5 1.5 0 0 1 2 2.5h7A1.5 1.5 0 0 1 10.5 4v1.5a.5.5 0 0 1-1 0V4a.5.5 0 0 0-.5-.5H2a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5v-1.5a.5.5 0 0 1 1 0V12A1.5 1.5 0 0 1 9 13.5H2z"/>
                    </svg>
                </a>
                {% else %}
                <a class="btn website-button discord-auth-link" href="{% url 'website:discord_auth_url' %}">Войти через Discord</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <main class="website-content">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="website-footer">
        {% block pagination %}
        {# News only #}
        {% endblock %}
        <div class="website-block text-center">
            <small>Developed by<a class="website-link" href="https://github.com/m1tr4b34st">m1tr4b34st</a></small>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {# {% if user.is_authenticated %} #}
    <script src="{% static 'js/api.js' %}"></script>
    {# {% else %} #}
    {# <scipt src="{% static 'js/unauthorized_api.js' %}"></scipt> #}
    {# {% endif %} #}
</body>
</html>

website/templates/website/error.html
{% extends 'website/base.html' %}

{% block menu %}
<ul class="navbar-nav mr-auto">
    <li class="nav-item">
        <a id="nickname-chat" class="nav-link website-nav-link" href="{% url 'website:index'}">Главная</a>
    </li>
    <li class="nav-item">
        <a class="nav-link website-nav-link" href="{% url 'website:news' %}">Новости проекта</a>
    </li>
</ul>
{% endblock %}

{% block content %}
<div class="website-block">
    <div class="alert website-error-message text-center">
        {% if error %}
        <span class="text-muted justify-content-start mr-2">{{ error.code }}</span> 
        <span class="justify-content-center">{{ error.text|linebreaksbr }}</span>
        {% if error.details %}
        <br />
        <span class="justify-content-center">{{ error.details|linebreaksbr }}</span>
        {% endif %}
        {% else %}
        Эта страница отрендерилась без ошибки... Скажу попроще, че ты тут делаешь???
        {% endif %}
    </div>
</div>
{% endblock %}

website/templates/website/index.html
{% extends 'website/base.html' %}

{% block menu %}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a id="nickname-chat" class="nav-link website-nav-link" href="{% url 'website:index'}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link website-nav-link" href="{% url 'website:news' %}">Новости проекта</a>
                    </li>
                </ul>
{% endblock %}

{% block content %}
<div class="website-block"> <!-- description -->
    Тут описание проекта
    <a href="sfvf" class="website-link">vsfvsfvs</a>
</div>
{% if user.is_authenticated and discord_user %}
<div class="row">
    <div class="col-md-6">
        <div class="website-block"> <!-- username chat form -->
            <form class="website-form">
                {% csrf_token %}
                <div class="d-flex">
                    <label for="nickname" class="justify-content-start col-form-label">Никнейм:</label>
                    <div class="w-100 mx-2 justify-content-center">
                        <input id="nickname" type="text" name="nickname" class="form-control website-form-control" maxlength="32">
                        <a id="set-original-nickname" class="text-muted small website-link">Оригинальный никнейм</a>
                        <br/>
                        <span id="nickname-error" class="small website-link website-error-text"></span>
                        <span id="nickname-hint" class="small website-link website-hint-text"></span>
                        <span id="nickname-info" class="small website-link website-info-text"></span>
                    </div>
                    <div class="justify-content-end">
                        <a id="update-nickname" class="btn website-button">Обновить</a>
                    </div>
                </div>
            </form>
        </div>
        <ul id="message-history" class="website-block website-message-history"> <!-- messages history -->
            {% include 'website/message_history.html' %}
        </ul>
    </div>
    <div class="col-md-6">
        <div class="website-block"> <!-- dynamic username form -->
            <div class="alert website-info-message d-flex">
              <span class="justify-content-center">Функция динамического никнейма находится в разработке.</span>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="website-block">
    <a class="website-link discord-auth-link" href="{% url 'website:discord_auth_url' %}">Войдите с помощью Discord</a>, чтобы получить доступ к функционалу.
</div>
{% endif %}
{% endblock %}

website/templates/website/message_history.html
{% if last_messages %}
{% for message in last_messages %}
<li class="alert website-message d-flex">
    <span class="text-muted mr-2">{{ message.sent|date:"d/m/y P" }}</span> 
    <span class="website-message-text">{{ message.text }}</span>
</li>
{% endfor %}
{% else %}
<li class="alert website-warn-message d-flex">
    <span class="website-message-text">
        Нет сообщений в базе.
    </span>
</li>
{% endif %}

website/templates/website/news.html
{% extends 'website/base.html' %}

{% block menu %}
<ul class="navbar-nav mr-auto">
    <li class="nav-item">
        <a id="nickname-chat" class="nav-link website-nav-link" href="{% url 'website:index' %}">Главная</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link website-nav-link" href="{% url 'website:news' %}">Новости проекта</a>
    </li>
</ul>
{% endblock %}

{% block content %}
<div class="website-block"> <!-- dynamic username form -->
    <div class="alert website-info-message d-flex">
      <span claslis="justify-content-center">Раздел новостей находится в разработке.</span>
    </div>
</div>
{% endblock %}

{% block pagination %}
{% if false %}
<div class="website-block">
                        
</div>
{% endif %}
{% endblock %}

website/templates/website/user.html
{% extends 'website/base.html' %}

{% block menu %}
<ul class="navbar-nav mr-auto">
    <li class="nav-item">
        <a id="nickname-chat" class="nav-link website-nav-link" href="{% url 'website:index'}">Главная</a>
    </li>
    <li class="nav-item">
        <a class="nav-link website-nav-link" href="{% url 'website:news' %}">Новости проекта</a>
    </li>
</ul>
{% endblock %}

{% block content %}
{% if user.is_authenticated and discord_user %}
<div class="row">
    <div class="col-md-2">
        <div class="website-block">
            <img src="{{ discord_user.avatar_url }}" alt="avatar" height="120px" width="120px">
        </div>
    </div>
    <div class="col-md-10">
        <div class="website-block">
            <div class="alert website-info-message">
                <span class="text-muted justify-content-start mr-2">
                    (id: {{ discord_user.discord_user_id }})
                </span> 
                <span class="justify-content-center">
                    @{{ discord_user.username }}
                </span>
            </div>
        </div>
        <div class="d-flex justify-content-around">
            <ul id="message-history" class="website-block website-message-history w-100 mx-1"> <!-- messages history -->
                {% include 'website/message_history.html' %}
            </ul>
            <div class="website-block w-100 mx-1">
                <div class="alert website-info-message d-flex">
                  <span class="justify-content-center">Функция динамического никнейма находится в разработке.</span>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="alert website-warn-message text-center">
    Ошибка получения информации о пользователе Discord.
</div>
{% endif %}
{% endblock %}